# -*- coding: utf-8 -*-
"""WikiPaste.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1C9U4lB9rwLViCrqRJ0XoplpUszuN8i
"""

from bs4 import BeautifulSoup
import requests

url = 'https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB_I'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')
print(soup.title)
everything = []
relatives = []
everything = soup.find_all('tr')
for i in everything:
    if str(i).find('Отец') >0:
        relatives.append(i)
      
    if str(i).find('Мать') >0:
        relatives.append(i)
    
    if str(i).find('Супруг') >0:
        relatives.append(i)
    
    if str(i).find('Дети') >0:
        relatives.append(i)

links = []
relativesnames = []

for i in relatives:
  a = list(i.text)

  b = 2
  while b!=len(a):
    if a[b].isupper() and a[b-1] != ('-') and a[b-1] != (' ') and a[b]!= "I":
      a.insert(b,"$")
      b = b + 1
    b = b + 1

  while True:
    try:
      a.remove('\n')
    except:
      break
  a = ''.join(a)
  a = a.split('$')
  relativesnames.append(a)

  position = str(i).find("/wiki/")
  if(position == -1):
    links.append("\nNone")
  b = 0
  while position > 0:
    if b == 0:
      links.append("\n")
    else:
      links.append("^^^")
    while list(str(i))[position] != '"' :
                links.append(list(str(i))[position])
                position = position + 1
    position = str(i).find("/wiki/",position)
    b = b + 1


links = ''.join(links)
links = links.split('\n')
b = 1
while b!= len(links):
  links[b] = links[b].split('^^^')
  b = b + 1
try:
  links.remove("")
except:
  0
print(relativesnames)
print(links)

https://ru.wikipedia.org/wiki/%D0%9F%D1%91%D1%82%D1%80_III
https://ru.wikipedia.org/wiki/%D0%98%D0%BE%D0%B3%D0%B0%D0%BD%D0%BD%D0%B0_%D0%95%D0%BB%D0%B8%D0%B7%D0%B0%D0%B2%D0%B5%D1%82%D0%B0_%D0%93%D0%BE%D0%BB%D1%8C%D1%88%D1%82%D0%B5%D0%B9%D0%BD-%D0%93%D0%BE%D1%82%D1%82%D0%BE%D1%80%D0%BF%D1%81%D0%BA%D0%B0%D1%8F